### ISSUE TITLE
Include Architecture Diagram in Main Page

### ISSUE THREAD

**Issue by gallogiulia** [MSUSAzureAccelerators/Intelligent-Supply-Chain-Management#1]
Use the architecture diagram in this article as inspiration:

https://learn.microsoft.com/en-us/azure/architecture/example-scenario/analytics/optimize-inventory-forecast-demand

**Comment by chulahlou** [comment]
@gallogiulia  where are we with this task? Would be helpful to add link to this article on the main page too.

**Comment by gallogiulia** [comment]
Done
